language: java

before_script:
- chmod 755 script/prepareJmeter.sh
- chmod 755 script/executeTest.sh
- script/prepareJmeter.sh

script:
- jmeter/apache-jmeter-3.0/bin/jmeter -n -t test/smoke.jmx -l jmeter.csv

# addons:
# artifacts: true
#  paths:
#  - $HOME/jmeter.csv
#  - $home/perfmon.csv
